version: '3'
services:
  # 消息队列
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    restart: always
    ports:
      - 4160:4160 # TCP 端口
      - 4161:4161 # HTTP 端口
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --data-path=/data
    restart: always
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150 # TCP 端口
      - 4151:4151 # HTTP 端口
    volumes:
      - './volumes/nsq:/data'
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    restart: always
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171 # HTTP 端口, 管理员端口应该往外加一层限制访问

networks:
  default:
    external:
      name: database_default
