version: '3'
services:
  # 数据库
#  pg:
#    image: postgres:13.3-alpine
#    restart: always
#    volumes:
#      - './volumes/pg:/var/lib/postgresql/data'
#    ports:
#      - 65432:5432
#    environment:
#      - POSTGRES_USER=root # 用户名
#      - POSTGRES_PASSWORD=root # 数据库密码
#      - POSTGRES_DB=gotest # 数据库名
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - './volumes/mysql/conf.d:/etc/mysql/conf.d'
      - './volumes/mysql/data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root


  # 缓存
  redis:
    image: redis:6.2.5-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - './volumes/redis:/data'
    #    environment:
    #      - REDIS_PASSWORD=password
    #    command: [ "redis-server", "--requirepass", "password" ]
    command: ['redis-server']
