// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devhg/kratos-example/internal/biz"
	"github.com/devhg/kratos-example/internal/conf"
	"github.com/devhg/kratos-example/internal/data"
	"github.com/devhg/kratos-example/internal/server"
	"github.com/devhg/kratos-example/internal/service"
	"github.com/go-kratos/kratos/v2"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger *zap.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo, logger)
	blogService := service.NewBlogService(articleUsecase, logger)
	commentRepo := data.NewCommentRepo(dataData, logger)
	commentUsecase := biz.NewCommentUsecase(commentRepo, logger)
	commentService := service.NewCommentService(logger, commentUsecase)
	httpServer := server.NewHTTPServer(confServer, logger, blogService, commentService)
	grpcServer := server.NewGRPCServer(confServer, logger, blogService, commentService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
